---
- name: "set minishift facts"
  block:
    - shell: "minishift console --url"
      register: minishift_console_output
    - set_fact:
        cluster_url_override: "{{ minishift_console_output.stdout }}"
    - shell: "oc config view -o jsonpath=\'{.users[?(.name==\"srang/\'$(minishift ip | sed \'s/\\./-/g\')\':8443\")].user.token}\'"
      register: minishift_config_output
    - set_fact:
        cluster_token_override: "{{ minishift_config_output.stdout }}"
  when:
    - minishift

- name: "set env facts"
  block:
    - set_fact:
        cluster_url: "{{ cluster_url_override | default(default_envs[env_type]['cluster_url']) }}"
        cluster_token: "{{ cluster_token_override | default(env.cluster_token) }}"
        size: "{{ env[env_purpose]['size'] }}"
    - set_fact:
        quotas: "{{ tshirts[size] }}"

- name: "set rolebinding facts"
  block:
    - set_fact:
        role_bindings: "{{ env[env_purpose]['access'] | default(omit) }}"
#    - set_fact:
#        admin_users:  "{{ env[env_purpose]['access']['users']  | json_query('[?type==`admin`].name') | default(omit) }}"
#        edit_users:   "{{ env[env_purpose]['access']['users']  | json_query('[?type==`edit`].name')  | default(omit) }}"
#        read_users:   "{{ env[env_purpose]['access']['users']  | json_query('[?type==`read`].name')  | default(omit) }}"
#    - set_fact:
#        admin_groups: "{{ env[env_purpose]['access']['groups'] | json_query('[?type==`admin`].name') | default(omit) }}"
#        edit_groups:  "{{ env[env_purpose]['access']['groups'] | json_query('[?type==`edit`].name')  | default(omit) }}"
#        read_groups:  "{{ env[env_purpose]['access']['groups'] | json_query('[?type==`read`].name')  | default(omit) }}"
#    - set_fact:
#        role_bindings: "{{  }}"

- name: "set namespace purpose facts"
  block:
    - set_fact:
        node_selector: "{{ default_purpose[env_purpose]['node_selector'] | default(omit) }}"

- name: "debug everything"
  debug:
    msg:
      - "minishift: {{ minishift }}"
      - "cluster_url: {{ cluster_url }}"
      - "cluster_token: {{ cluster_token }}"
      - "size: {{ size }}"
      - "quota: {{ quotas }}"
      - "node_selector: {{ node_selector }}"
