---
- name: "Provision {{ env.env_type }} build namespace"
  include_tasks: namespace-provision.yaml
  vars:
    env_purpose: build
    ocp_project_name: "{{ project_name }}-build"
    env_type: "{{ env.env_type }}"
  when:
    - env['build']['enabled']

- name: "Provision {{ env.env_type }} deploy namespace"
  include_tasks: namespace-provision.yaml
  vars:
    env_purpose: deploy
    ocp_project_name: "{{ project_name }}"
    env_type: "{{ env.env_type }}"
  when:
    - env['deploy']['enabled']