---
- name: "first test"
  debug:
    msg: "env: {{ kubeconfig }} {{ env_name }}"
- name: "print out cluster_url"
  debug:
    msg: "value: {{ cluster_url }}"

- name: "ensure namespace"
  oc_project:
    name: "dotnet-example"
    state: present
    display_name: "My Dotnet example"
    debug: true
    kubeconfig: "{{ kubeconfig }}"
- name: "set quotas"
  oc_obj:
    kubeconfig: "{{ kubeconfig }}"
    name: core-object-counts
    namespace: "dotnet-example"
    state: present
    kind: ResourceQuota
    content:
      path: /tmp/quota
      data: "{{ lookup('template', 'quota.yaml.j2') | from_yaml }}"