---
- name: "Provision {{ env.name }} build namespace"
  include_tasks:
    name: namespace-provision.yaml
  vars:
    env_purpose: build
    project_name: "{{ project_name }}-build"
    env_type: "{{ env.name }}"
  when:
    - env['build']['enabled']

- name: "Provision {{ env.name }} deploy namespace"
  include_tasks:
    name: namespace-provision.yaml
  vars:
    env_purpose: deploy
    env_type: "{{ env.name }}"
  when:
    - env['deploy']['enabled']