---
- include_tasks: facts.yaml

- name: "create namespace and resources {{ ocp_project_name }}"
  include_role:
    name: openshift-provision
  vars:
    openshift_clusters:
    - connection:
        server: "{{ cluster_url }}"
        token: "{{ cluster_token }}"
        insecure_skip_tls_verify: "True"
      projects:
        - name: "{{ ocp_project_name }}"
          labels:
            application: "{{ ocp_project_name }}"
            envtype: "{{ env_type }}"
            chargeback_code: "{{ chargeback_code }}"
          node_selector: "{{ node_selector }}"
          role_bindings: "{{ role_bindings }}"
#            - role: admin
#              users:
#                - "{{ admin_users  | default(omit) }}"
#              groups:
#                - "{{ admin_groups | default(omit) }}"
#            - role: edit
#              users:
#                - "{{ edit_users   | default(omit) }}"
#              groups:
#                - "{{ edit_groups  | default(omit) }}"
#            - role: read
#              users:
#                - "{{ read_users   | default(omit) }}"
#              groups:
#                - "{{ read_groups  | default(omit) }}"
          serviceaccounts:
            - jenkins
          resources:
          - apiVersion: v1
            kind: ResourceQuota
            metadata:
              name: compute-resources-time-bound
            spec:
              hard: "{{ quotas }}"
          - apiVersion: v1
            kind: LimitRange
            metadata:
              name: core-resource-limits
            spec:
              limits:
              - type: Container
                default:
                  cpu: "1"
                  memory: "2Gi"
                default_request:
                  cpu: "100m"
                  memory: "1Gi"
                max:
                  cpu: "4"
                  memory: "10Gi"
                min:
                  cpu: "100m"
                  memory: "10Mi"