token_vars:
  dev:
envs:
  - env_type: dev
    cluster_token: "{{ token_vars['dev'] }}"
    build:
      enabled: true
      size: medium
      access:
        - role: admin
          users:
            - srang
            - system:serviceaccount:openshift:provisioner
        - role: edit
          users:
            - system:serviceaccount:{{ project_name }}:default
          groups:
            - developers
    deploy:
      enabled: true
      size: small
      access:
        - role: admin
          users:
            - srang
            - system:serviceaccount:openshift:provisioner
        - role: edit
          users:
            - system:serviceaccount:{{ project_name }}-build:default
        - role: read
          groups:
            - developers